import streamlit as st
from agent_core import run_research, chat_with_ai, solve_math
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_CENTER
import io
from datetime import datetime

def generate_pdf(topic, report_text):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
        rightMargin=2*cm, leftMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm)
    story = [
        Paragraph("AI Research Agent", ParagraphStyle("t",
            fontName="Helvetica-Bold", fontSize=20,
            textColor=colors.HexColor("#2563eb"),
            alignment=TA_CENTER, spaceAfter=8)),
        Paragraph(f"Report: {topic}", ParagraphStyle("tp",
            fontName="Helvetica-Bold", fontSize=13,
            textColor=colors.HexColor("#1e293b"),
            alignment=TA_CENTER, spaceAfter=6)),
        Paragraph("Generated by ResearchAI", ParagraphStyle("m",
            fontName="Helvetica-Oblique", fontSize=9,
            textColor=colors.HexColor("#64748b"),
            alignment=TA_CENTER, spaceAfter=16)),
        HRFlowable(width="100%", thickness=0.8,
            color=colors.HexColor("#2563eb"), spaceAfter=14),
    ]
    bs = ParagraphStyle("b", fontName="Helvetica", fontSize=10,
        leading=16, textColor=colors.HexColor("#1e293b"), spaceAfter=6)
    for line in report_text.split('\n'):
        line = line.strip().replace('**','').replace('•','-')
        story.append(Paragraph(line, bs) if line else Spacer(1,5))
    doc.build(story)
    buffer.seek(0)
    return buffer

if "dark_mode"      not in st.session_state: st.session_state.dark_mode      = False
if "history"        not in st.session_state: st.session_state.history        = []
if "current_report" not in st.session_state: st.session_state.current_report = None
if "page"           not in st.session_state: st.session_state.page           = "home"
if "research_topic" not in st.session_state: st.session_state.research_topic = ""
if "chat_messages"  not in st.session_state: st.session_state.chat_messages  = []
if "chat_tab"       not in st.session_state: st.session_state.chat_tab       = "chat"

st.set_page_config(page_title="ResearchAI", page_icon="🔬",
                   layout="wide", initial_sidebar_state="collapsed")

dark = st.session_state.dark_mode

BG       = "#0d1117"      if dark else "#f9fafb"
CARD_BG  = "#161b22"      if dark else "#ffffff"
CARD2    = "#21262d"      if dark else "#f3f4f6"
TEXT     = "#e6edf3"      if dark else "#111827"
SUBTEXT  = "#8b949e"      if dark else "#6b7280"
BORDER   = "#30363d"      if dark else "#e5e7eb"
ACCENT   = "#2563eb"
NAV_BG   = "#161b22"      if dark else "#ffffff"
INPUT_BG = "#0d1117"      if dark else "#ffffff"
HOVER    = "rgba(37,99,235,0.12)" if dark else "rgba(37,99,235,0.06)"
SHADOW   = "rgba(0,0,0,0.5)"      if dark else "rgba(0,0,0,0.06)"
T_BG     = "#2563eb"      if dark else "#e5e7eb"
T_POS    = "22px"         if dark else "2px"
T_ICON   = "🌙"           if dark else "☀️"

st.markdown(f"""
<style>
*,*::before,*::after{{box-sizing:border-box;margin:0;padding:0;}}
.stApp,[data-testid="stAppViewContainer"],[data-testid="stAppViewBlockContainer"],
[data-testid="stMain"],.main{{background-color:{BG}!important;color:{TEXT}!important;}}
header[data-testid="stHeader"],[data-testid="stToolbar"],[data-testid="stDecoration"],
[data-testid="stStatusWidget"],.stDeployButton,#MainMenu,footer,
.viewerBadge_container__r5tak{{display:none!important;}}
.block-container{{padding:0!important;max-width:100%!important;}}
section.main>div{{padding:0!important;}}
section[data-testid="stSidebar"]{{display:none!important;}}
[data-testid="collapsedControl"]{{display:none!important;}}
p,h1,h2,h3,h4,span,label,li{{color:{TEXT}!important;}}
.stTextInput>div>div>input{{background:{INPUT_BG}!important;
  border:1.5px solid {BORDER}!important;border-radius:10px!important;
  color:{TEXT}!important;font-size:1rem!important;
  padding:0.7rem 1.2rem!important;width:100%!important;}}
.stTextInput>div>div>input:focus{{border-color:{ACCENT}!important;
  box-shadow:0 0 0 3px rgba(37,99,235,0.12)!important;}}
.stTextInput>div>div>input::placeholder{{color:{SUBTEXT}!important;}}
.stTextInput label{{display:none!important;}}
.stButton>button{{background:transparent!important;color:{SUBTEXT}!important;
  border:none!important;font-size:0.88rem!important;font-weight:500!important;
  padding:0.42rem 0.9rem!important;border-radius:7px!important;
  transition:all 0.18s!important;width:auto!important;cursor:pointer!important;}}
.stButton>button:hover{{background:{HOVER}!important;color:{ACCENT}!important;}}
button[kind="primary"]{{background:{ACCENT}!important;color:white!important;
  border:none!important;font-weight:700!important;font-size:0.95rem!important;
  padding:0.65rem 2rem!important;border-radius:10px!important;width:100%!important;
  box-shadow:0 4px 14px rgba(37,99,235,0.3)!important;transition:all 0.2s!important;}}
button[kind="primary"]:hover{{opacity:0.88!important;transform:translateY(-1px)!important;}}
.stDownloadButton>button{{background:transparent!important;color:{ACCENT}!important;
  border:2px solid {ACCENT}!important;border-radius:8px!important;
  font-weight:600!important;padding:0.5rem 1rem!important;width:100%!important;}}
.stDownloadButton>button:hover{{background:{ACCENT}!important;color:white!important;}}
.stSpinner>div{{border-top-color:{ACCENT}!important;}}
.card{{background:{CARD_BG};border:1px solid {BORDER};border-radius:14px;
  padding:1.5rem;margin-bottom:1rem;box-shadow:0 2px 8px {SHADOW};}}
.feat-grid{{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin-top:2rem;}}
.feat-card{{background:{CARD_BG};border:1px solid {BORDER};border-radius:14px;
  padding:1.8rem 1rem;text-align:center;transition:all 0.22s;
  box-shadow:0 1px 4px {SHADOW};}}
.feat-card:hover{{border-color:{ACCENT};
  box-shadow:0 6px 20px rgba(37,99,235,0.15);transform:translateY(-3px);}}
.feat-icon{{font-size:2.2rem;margin-bottom:0.6rem;}}
.feat-title{{font-weight:700;font-size:1rem;color:{TEXT};}}
.feat-desc{{font-size:0.83rem;color:{SUBTEXT};margin-top:0.35rem;}}
.step-card{{background:{CARD_BG};border:1px solid {BORDER};border-radius:14px;
  padding:1.8rem 1rem;text-align:center;box-shadow:0 1px 4px {SHADOW};}}
.step-num{{background:{ACCENT};color:white!important;width:40px;height:40px;
  border-radius:50%;display:flex;align-items:center;justify-content:center;
  font-weight:700;font-size:1.1rem;margin:0 auto 0.8rem auto;}}
.step-title{{font-weight:700;font-size:0.95rem;}}
.step-desc{{font-size:0.82rem;color:{SUBTEXT};margin-top:0.4rem;}}
.hist-item{{padding:0.65rem 0.85rem;border-radius:8px;margin-bottom:0.4rem;
  border:1px solid {BORDER};background:{BG};transition:all 0.18s;}}
.hist-item:hover{{border-color:{ACCENT};background:{HOVER};}}
.hist-title{{font-size:0.82rem;font-weight:600;}}
.hist-date{{font-size:0.73rem;color:{SUBTEXT};margin-top:2px;}}
.badge{{display:block;background:rgba(37,99,235,0.08);color:{ACCENT}!important;
  border-radius:6px;padding:0.28rem 0.65rem;font-size:0.8rem;
  font-weight:600;margin-bottom:0.5rem;}}
.report-text{{font-size:0.95rem;line-height:1.8;color:{TEXT};white-space:pre-wrap;}}
.stat-grid{{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin:1.5rem 0;}}
.stat-card{{background:{CARD_BG};border:1px solid {BORDER};border-radius:12px;
  padding:1.2rem;text-align:center;box-shadow:0 1px 4px {SHADOW};}}
.stat-num{{font-size:1.8rem;font-weight:800;color:{ACCENT};margin-bottom:0.2rem;}}
.stat-label{{font-size:0.82rem;color:{SUBTEXT};}}
.badge-new{{display:inline-block;background:linear-gradient(135deg,#10b981,#059669);
  color:white!important;font-size:0.7rem;font-weight:700;padding:0.15rem 0.5rem;
  border-radius:20px;margin-left:0.4rem;vertical-align:middle;}}
/* Toggle */
.toggle-track{{width:48px;height:26px;background:{T_BG};border-radius:13px;
  position:relative;transition:background 0.3s;display:inline-flex;
  align-items:center;cursor:pointer;border:1px solid rgba(255,255,255,0.1);}}
.toggle-dot{{width:22px;height:22px;background:white;border-radius:50%;
  position:absolute;left:{T_POS};transition:left 0.3s;
  box-shadow:0 1px 4px rgba(0,0,0,0.3);display:flex;
  align-items:center;justify-content:center;font-size:12px;}}
</style>
""", unsafe_allow_html=True)

# ── TOP NAVBAR ────────────────────────────────────────────────────────────────
st.markdown(f"""
<style>
/* ---- Navbar wrapper ---- */
.navbar-outer{{
  position:sticky;top:0;z-index:999;
  background:{NAV_BG};
  border-bottom:1px solid {BORDER};
  box-shadow:0 2px 14px {SHADOW};
  width:100%;
}}
/* Hide all default Streamlit chrome inside navbar */
.navbar-outer .stButton>button{{
  background:transparent!important;
  border:none!important;
  color:{SUBTEXT}!important;
  font-size:0.88rem!important;
  font-weight:500!important;
  padding:0.36rem 1.05rem!important;
  border-radius:24px!important;
  transition:all 0.17s!important;
  white-space:nowrap!important;
  box-shadow:none!important;
}}
.navbar-outer .stButton>button:hover{{
  background:{'rgba(255,255,255,0.09)' if dark else 'rgba(0,0,0,0.07)'}!important;
  color:{TEXT}!important;
}}
/* Logo */
.nav-logo-txt{{
  font-size:1.18rem;font-weight:800;
  color:{ACCENT};white-space:nowrap;
  padding:0 0.5rem;
}}
/* Pills container */
.nav-pills-box{{
  display:flex;align-items:center;
  background:{'rgba(255,255,255,0.06)' if dark else 'rgba(0,0,0,0.05)'};
  border-radius:30px;padding:3px 5px;
  gap:1px;
}}
/* GitHub button */
.gh-link-btn{{
  background:{ACCENT}!important;
  color:#ffffff!important;
  padding:0.4rem 1.15rem!important;
  border-radius:22px!important;
  font-weight:700!important;
  font-size:0.86rem!important;
  border:none!important;
  text-decoration:none;
  display:inline-block;
  transition:opacity 0.18s;
}}
.gh-link-btn:hover{{opacity:0.82;}}
</style>
""", unsafe_allow_html=True)

# Logo + nav pill buttons + github in one row
_logo_col, _pills_col, _gh_col = st.columns([1.8, 3, 1.5])

with _logo_col:
    st.markdown(f"<div class='nav-logo-txt' style='padding:1rem 0.5rem;'>🔬 ResearchAI</div>",
                unsafe_allow_html=True)

with _pills_col:
    st.markdown("<div class='nav-pills-box'>", unsafe_allow_html=True)
    _pb1, _pb2, _pb3, _pb4 = st.columns([1,1,1.3,1])
    with _pb1:
        if st.button("🏠 Home", key="nav_home"):
            st.session_state.page = "home"
            st.session_state.current_report = None
            st.rerun()
    with _pb2:
        if st.button("🔍 Research", key="nav_research"):
            st.session_state.page = "research"
            st.session_state.current_report = None
            st.rerun()
    with _pb3:
        if st.button("❓ How it Works", key="nav_how"):
            st.session_state.page = "how"
            st.session_state.current_report = None
            st.rerun()
    with _pb4:
        if st.button(f"{T_ICON} {'Dark' if not dark else 'Light'}", key="nav_theme"):
            st.session_state.dark_mode = not dark
            st.rerun()
    st.markdown("</div>", unsafe_allow_html=True)

with _gh_col:
    st.markdown(
        f"""<div style='display:flex;justify-content:flex-end;align-items:center;padding:0.6rem 0.5rem;'>
        <a href='https://github.com/nevedhya03-dotcom' target='_blank' class='gh-link-btn'>
            GitHub &rarr;
        </a></div>""",
        unsafe_allow_html=True)

# ── Content wrapper ────────────────────────────────────────────────────────────
st.markdown(f"<div style='padding:0 2rem;'>", unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════════════════════
# HOME PAGE
# ══════════════════════════════════════════════════════════════════════════════
if st.session_state.page == "home" and not st.session_state.current_report:

    st.markdown(f"""
    <div style='text-align:center; padding:2.5rem 0 1.5rem 0;'>
        <div style='display:inline-block; background:rgba(37,99,235,0.1);
                    color:{ACCENT}; font-size:0.82rem; font-weight:600;
                    padding:0.3rem 1rem; border-radius:20px; margin-bottom:1rem;
                    border:1px solid rgba(37,99,235,0.2);'>
            🚀 Powered by Groq LLaMA3 + Tavily Search API
        </div>
        <h1 style='font-size:2.8rem; font-weight:800; color:{TEXT};
                   line-height:1.22; margin-bottom:1rem;'>
            Write Better Reports with
            <span style='color:{ACCENT};'> ResearchAI</span>
        </h1>
        <p style='color:{SUBTEXT}; font-size:1.05rem;
                  max-width:560px; margin:0 auto; line-height:1.7;'>
            Enter any topic and our AI agent will search the internet,
            analyze multiple sources, and write a professional
            research report — <b style='color:{TEXT};'>instantly.</b>
        </p>
    </div>
    """, unsafe_allow_html=True)

    st.markdown(f"""
    <div class="stat-grid">
        <div class="stat-card">
            <div class="stat-num">30s</div>
            <div class="stat-label">Average research time</div>
        </div>
        <div class="stat-card">
            <div class="stat-num">5+</div>
            <div class="stat-label">Web sources analyzed</div>
        </div>
        <div class="stat-card">
            <div class="stat-num">100%</div>
            <div class="stat-label">Free to use</div>
        </div>
    </div>
    """, unsafe_allow_html=True)

    c1,c2,c3 = st.columns([0.8,2.5,0.8])
    with c2:
        topic = st.text_input("",
            placeholder="✏️  e.g. Latest trends in Generative AI 2026",
            label_visibility="collapsed", key="search_input")
        search_btn = st.button("🔍  Start Research",
                               type="primary", key="search_btn")

    st.markdown(f"""
    <div class="feat-grid">
        <div class="feat-card">
            <div class="feat-icon">⚡</div>
            <div class="feat-title">Time-Saving
                <span class="badge-new">FAST</span></div>
            <div class="feat-desc">
                Full research reports in under 30 seconds</div>
        </div>
        <div class="feat-card">
            <div class="feat-icon">🎯</div>
            <div class="feat-title">High Accuracy</div>
            <div class="feat-desc">
                Real-time web search via Tavily API</div>
        </div>
        <div class="feat-card">
            <div class="feat-icon">📄</div>
            <div class="feat-title">PDF Export
                <span class="badge-new">NEW</span></div>
            <div class="feat-desc">
                Download professional PDF reports instantly</div>
        </div>
    </div>
    """, unsafe_allow_html=True)

    if search_btn and topic:
        with st.spinner("🤖 AI Agent is researching... ⏳"):
            try:
                report, steps = run_research(topic)
                st.session_state.history.append({
                    "topic": topic, "report": report,
                    "steps": steps,
                    "time": datetime.now().strftime("%b %d, %H:%M")
                })
                st.session_state.current_report = {
                    "topic": topic, "report": report, "steps": steps
                }
                st.rerun()
            except Exception as e:
                st.error(f"❌ Error: {str(e)}")
    elif search_btn:
        st.warning("⚠️ Please enter a research topic!")

    # ── AI Info Section ──────────────────────────────────────────────────────
    st.markdown(f"""
    <div style='margin-top:3.5rem;'>
      <div style='text-align:center;margin-bottom:1.8rem;'>
        <h2 style='font-size:1.75rem;font-weight:800;color:{TEXT};'>About AI-Powered Research</h2>
        <p style='color:{SUBTEXT};font-size:0.95rem;max-width:560px;margin:0.5rem auto;'>
          ResearchAI combines state-of-the-art language models with real-time web search
          to deliver accurate, comprehensive reports in seconds.
        </p>
      </div>
      <div style='display:grid;grid-template-columns:repeat(2,1fr);gap:1.2rem;margin-bottom:2rem;'>
        <div style='background:{CARD_BG};border:1px solid {BORDER};border-radius:14px;padding:1.5rem;'>
          <div style='font-size:1.5rem;margin-bottom:0.5rem;'>🧠</div>
          <div style='font-weight:700;color:{TEXT};margin-bottom:0.4rem;'>Large Language Models</div>
          <div style='font-size:0.85rem;color:{SUBTEXT};line-height:1.6;'>
            Powered by Groq's ultra-fast inference running Meta's LLaMA 3 model —
            capable of synthesizing complex information into coherent, structured reports.
          </div>
        </div>
        <div style='background:{CARD_BG};border:1px solid {BORDER};border-radius:14px;padding:1.5rem;'>
          <div style='font-size:1.5rem;margin-bottom:0.5rem;'>🌐</div>
          <div style='font-weight:700;color:{TEXT};margin-bottom:0.4rem;'>Real-Time Web Search</div>
          <div style='font-size:0.85rem;color:{SUBTEXT};line-height:1.6;'>
            Tavily Search API fetches live, relevant sources from the web — ensuring
            your reports reflect the latest available information, not outdated training data.
          </div>
        </div>
        <div style='background:{CARD_BG};border:1px solid {BORDER};border-radius:14px;padding:1.5rem;'>
          <div style='font-size:1.5rem;margin-bottom:0.5rem;'>🔗</div>
          <div style='font-weight:700;color:{TEXT};margin-bottom:0.4rem;'>Agentic Workflow</div>
          <div style='font-size:0.85rem;color:{SUBTEXT};line-height:1.6;'>
            LangGraph orchestrates multi-step agent reasoning — the AI decides what to
            search, how to interpret results, and structures the output intelligently.
          </div>
        </div>
        <div style='background:{CARD_BG};border:1px solid {BORDER};border-radius:14px;padding:1.5rem;'>
          <div style='font-size:1.5rem;margin-bottom:0.5rem;'>📊</div>
          <div style='font-weight:700;color:{TEXT};margin-bottom:0.4rem;'>Structured Reports</div>
          <div style='font-size:0.85rem;color:{SUBTEXT};line-height:1.6;'>
            Every report is formatted with sections, summaries, and key takeaways —
            and can be exported as a professional PDF with one click.
          </div>
        </div>
      </div>
    </div>
    """, unsafe_allow_html=True)

    # ── Pipeline Flowchart (SVG) ─────────────────────────────────────────────
    arrow_col = ACCENT
    box_bg = CARD_BG
    box_border = BORDER
    txt_c = TEXT
    sub_c = SUBTEXT
    st.markdown(f"""
    <div style='text-align:center;margin-bottom:1rem;'>
      <div style='font-weight:700;font-size:1.1rem;color:{TEXT};margin-bottom:1rem;'>⚙️ How the Agent Pipeline Works</div>
      <svg viewBox='0 0 900 140' xmlns='http://www.w3.org/2000/svg'
           style='width:100%;max-width:900px;height:auto;overflow:visible;'>
        <!-- Boxes -->
        <rect x='20' y='35' width='140' height='60' rx='12' fill='{box_bg}' stroke='{arrow_col}' stroke-width='1.5'/>
        <text x='90' y='61' text-anchor='middle' fill='{txt_c}' font-size='13' font-weight='700'>📝 User Topic</text>
        <text x='90' y='80' text-anchor='middle' fill='{sub_c}' font-size='10'>Enter a subject</text>
        <!-- Arrow 1 -->
        <line x1='160' y1='65' x2='196' y2='65' stroke='{arrow_col}' stroke-width='2' marker-end='url(#arr)'/>
        <!-- Box 2 -->
        <rect x='196' y='35' width='140' height='60' rx='12' fill='{box_bg}' stroke='{arrow_col}' stroke-width='1.5'/>
        <text x='266' y='61' text-anchor='middle' fill='{txt_c}' font-size='13' font-weight='700'>🔍 Web Search</text>
        <text x='266' y='80' text-anchor='middle' fill='{sub_c}' font-size='10'>Tavily API</text>
        <!-- Arrow 2 -->
        <line x1='336' y1='65' x2='372' y2='65' stroke='{arrow_col}' stroke-width='2' marker-end='url(#arr)'/>
        <!-- Box 3 -->
        <rect x='372' y='35' width='160' height='60' rx='12' fill='{box_bg}' stroke='{arrow_col}' stroke-width='1.5'/>
        <text x='452' y='61' text-anchor='middle' fill='{txt_c}' font-size='13' font-weight='700'>🧠 LLM Analysis</text>
        <text x='452' y='80' text-anchor='middle' fill='{sub_c}' font-size='10'>Groq LLaMA3</text>
        <!-- Arrow 3 -->
        <line x1='532' y1='65' x2='568' y2='65' stroke='{arrow_col}' stroke-width='2' marker-end='url(#arr)'/>
        <!-- Box 4 -->
        <rect x='568' y='35' width='155' height='60' rx='12' fill='{box_bg}' stroke='{arrow_col}' stroke-width='1.5'/>
        <text x='645' y='61' text-anchor='middle' fill='{txt_c}' font-size='13' font-weight='700'>📄 Report Draft</text>
        <text x='645' y='80' text-anchor='middle' fill='{sub_c}' font-size='10'>Structured output</text>
        <!-- Arrow 4 -->
        <line x1='723' y1='65' x2='756' y2='65' stroke='{arrow_col}' stroke-width='2' marker-end='url(#arr)'/>
        <!-- Box 5 -->
        <rect x='756' y='35' width='128' height='60' rx='12' fill='{arrow_col}'/>
        <text x='820' y='61' text-anchor='middle' fill='white' font-size='13' font-weight='700'>⬇️ PDF Export</text>
        <text x='820' y='80' text-anchor='middle' fill='rgba(255,255,255,0.75)' font-size='10'>Download ready</text>
        <!-- Arrowhead marker -->
        <defs>
          <marker id='arr' markerWidth='8' markerHeight='8' refX='6' refY='3' orient='auto'>
            <path d='M0,0 L0,6 L8,3 z' fill='{arrow_col}'/>
          </marker>
        </defs>
      </svg>
    </div>
    """, unsafe_allow_html=True)

    # ── CTA to Research page ─────────────────────────────────────────────────
    st.markdown(f"""
    <div style='text-align:center;margin:2rem 0 1rem 0;'>
      <p style='color:{SUBTEXT};font-size:0.92rem;'>Ready to generate your first report?</p>
    </div>
    """, unsafe_allow_html=True)
    _cta1, _cta2, _cta3 = st.columns([1,1,1])
    with _cta2:
        if st.button("🔍  Go to Research Page →", type="primary", key="cta_research"):
            st.session_state.page = "research"
            st.rerun()

# ══════════════════════════════════════════════════════════════════════════════
# RESEARCH PAGE  (Dual-Mode: Chat AI + Deep Research)
# ══════════════════════════════════════════════════════════════════════════════
elif st.session_state.page == "research" and not st.session_state.current_report:

    # Mermaid.js injection (loads once per page render)
    st.markdown("""
    <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        if (window.mermaid) { mermaid.initialize({startOnLoad:true, theme:'dark'}); }
      });
      // Also try to init after a short delay for Streamlit dynamic rendering
      setTimeout(function() {
        if (window.mermaid) { mermaid.init(undefined, document.querySelectorAll('.mermaid')); }
      }, 800);
    </script>
    """, unsafe_allow_html=True)

    # ── Page header ──────────────────────────────────────────────────────────
    st.markdown(f"""
    <div style='text-align:center;padding:2rem 0 0.8rem 0;'>
      <h1 style='font-size:2.2rem;font-weight:800;color:{TEXT};line-height:1.25;margin-bottom:0.4rem;'>
        🤖 ResearchAI <span style='color:{ACCENT};'>Assistant</span>
      </h1>
      <p style='color:{SUBTEXT};font-size:0.95rem;max-width:520px;margin:0 auto;'>
        Chat with AI · Solve math · Generate flowcharts · Deep web research
      </p>
    </div>
    """, unsafe_allow_html=True)

    # ── Tab switcher ─────────────────────────────────────────────────────────
    st.markdown(f"""
    <style>
    .tab-bar{{display:flex;gap:0.5rem;margin:1rem 0 1.5rem 0;}}
    .tab-bar .stButton>button{{
      border-radius:22px!important;font-size:0.9rem!important;
      font-weight:600!important;padding:0.45rem 1.3rem!important;
    }}
    .chat-bubble-user{{
      display:flex;justify-content:flex-end;margin:0.5rem 0;
    }}
    .chat-bubble-user .bubble{{
      background:{ACCENT};color:white;
      border-radius:18px 18px 4px 18px;
      padding:0.75rem 1.1rem;max-width:72%;
      font-size:0.93rem;line-height:1.55;
    }}
    .chat-bubble-ai{{
      display:flex;justify-content:flex-start;margin:0.5rem 0;
      gap:0.6rem;align-items:flex-start;
    }}
    .chat-bubble-ai .avatar{{
      width:34px;height:34px;border-radius:50%;
      background:{ACCENT};display:flex;align-items:center;
      justify-content:center;font-size:1rem;flex-shrink:0;margin-top:2px;
    }}
    .chat-bubble-ai .bubble{{
      background:{CARD_BG};border:1px solid {BORDER};
      border-radius:4px 18px 18px 18px;
      padding:0.75rem 1.1rem;max-width:78%;
      font-size:0.93rem;line-height:1.6;color:{TEXT};
    }}
    .math-box{{
      background:rgba(37,99,235,0.1);border:1px solid rgba(37,99,235,0.3);
      border-radius:10px;padding:0.8rem 1.1rem;margin-top:0.6rem;
      font-family:monospace;color:{ACCENT};font-size:0.92rem;
    }}
    .mermaid{{
      margin-top:0.8rem;
      background:{CARD_BG}!important;
      border-radius:12px;padding:1rem;
    }}
    </style>
    """, unsafe_allow_html=True)

    t1, t2, t3 = st.columns([1.2, 1.5, 3])
    with t1:
        if st.button("💬 Chat AI",
                     type="primary" if st.session_state.chat_tab == "chat" else "secondary",
                     key="tab_chat"):
            st.session_state.chat_tab = "chat"
            st.rerun()
    with t2:
        if st.button("🔍 Deep Research",
                     type="primary" if st.session_state.chat_tab == "research" else "secondary",
                     key="tab_research"):
            st.session_state.chat_tab = "research"
            st.rerun()

    st.markdown("<hr style='border:none;border-top:1px solid " + BORDER + ";margin:0 0 1.2rem 0;'>",
                unsafe_allow_html=True)

    # ══════════════════════════════════════════════════════════════════════════
    # TAB 1 — CHAT AI
    # ══════════════════════════════════════════════════════════════════════════
    if st.session_state.chat_tab == "chat":

        if not st.session_state.chat_messages:
            st.markdown(f"""
            <div style='margin-bottom:1.2rem;'>
              <div style='color:{SUBTEXT};font-size:0.82rem;font-weight:600;
                          text-transform:uppercase;letter-spacing:0.05em;
                          margin-bottom:0.6rem;'>Try asking...</div>
              <div style='display:flex;flex-wrap:wrap;gap:0.5rem;'>
                {''.join([
                    f"<span style='background:{CARD_BG};border:1px solid {BORDER};"
                    f"border-radius:20px;padding:0.35rem 0.9rem;font-size:0.83rem;"
                    f"color:{SUBTEXT};'>{p}</span>"
                    for p in [
                        "Explain quantum computing simply",
                        "Solve x² - 5x + 6 = 0",
                        "Flowchart of how the internet works",
                        "What is machine learning?",
                        "Calculate 15% of 3,450",
                        "Diagram of photosynthesis process",
                    ]
                ])}
              </div>
            </div>
            """, unsafe_allow_html=True)

        import re
        import streamlit.components.v1 as components

        for msg in st.session_state.chat_messages:
            if msg["role"] == "user":
                st.markdown(f"""
                <div class='chat-bubble-user'>
                  <div class='bubble'>{msg['content']}</div>
                </div>""", unsafe_allow_html=True)
            else:
                content = msg["content"]
                mermaid_pattern = r'```mermaid\s*([\s\S]*?)```'
                parts = re.split(mermaid_pattern, content)

                for i, part in enumerate(parts):
                    if i % 2 == 0:
                        if part.strip():
                            st.markdown(f"""
                            <div class='chat-bubble-ai'>
                              <div class='avatar'>🤖</div>
                              <div class='bubble'>{part.strip()}</div>
                            </div>""", unsafe_allow_html=True)
                    else:
                        mermaid_theme = "dark" if dark else "default"
                        clean_mermaid = part.strip().replace('"', "'")
                        components.html(f"""
                        <!DOCTYPE html>
                        <html>
                        <head>
                          <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
                          <style>
                            body {{
                              background:{'#161b22' if dark else '#ffffff'};
                              margin:0; padding:1rem;
                            }}
                            .mermaid {{ text-align:center; }}
                            .error-box {{
                              background:rgba(239,68,68,0.1);
                              border:1px solid rgba(239,68,68,0.3);
                              border-radius:10px; padding:1rem;
                              color:#ef4444; font-size:0.85rem;
                            }}
                            .code-box {{
                              background:{'#21262d' if dark else '#f3f4f6'};
                              border-radius:8px; padding:0.8rem;
                              font-family:monospace; font-size:0.8rem;
                              color:{'#e6edf3' if dark else '#1e293b'};
                              white-space:pre-wrap; margin-top:0.5rem;
                            }}
                          </style>
                        </head>
                        <body>
                          <div id="diagram" class="mermaid">{clean_mermaid}</div>
                          <div id="fallback" style="display:none;">
                            <div class="error-box">
                              ⚠️ Could not render diagram. Raw code:
                              <div class="code-box">{clean_mermaid}</div>
                            </div>
                          </div>
                          <script>
                            mermaid.initialize({{
                              startOnLoad: false,
                              theme: '{mermaid_theme}',
                              securityLevel: 'loose'
                            }});
                            mermaid.run({{
                              nodes: [document.getElementById('diagram')]
                            }}).catch((err) => {{
                              document.getElementById('diagram').style.display='none';
                              document.getElementById('fallback').style.display='block';
                            }});
                          </script>
                        </body>
                        </html>
                        """, height=380, scrolling=True)

                if "math_result" in msg and msg["math_result"]:
                    st.markdown(f"""
                    <div class='chat-bubble-ai'>
                      <div class='avatar'>🔢</div>
                      <div class='bubble'>
                        <div class='math-box'>{msg['math_result']}</div>
                      </div>
                    </div>""", unsafe_allow_html=True)

        chat_col1, chat_col2 = st.columns([6, 1])
        with chat_col1:
            user_input = st.text_input("Message",
                placeholder="Ask anything — math, flowcharts, questions...",
                label_visibility="collapsed", key="chat_input")
        with chat_col2:
            send_btn = st.button("Send ➤", type="primary", key="send_btn")

        cl1, cl2 = st.columns([5, 1])
        with cl2:
            if st.session_state.chat_messages:
                if st.button("🗑 Clear", key="clear_chat"):
                    st.session_state.chat_messages = []
                    st.rerun()

        if send_btn and user_input:
            st.session_state.chat_messages.append({
                "role": "user", "content": user_input
            })
            with st.spinner("🤖 Thinking..."):
                try:
                    ai_reply = chat_with_ai(
                        st.session_state.chat_messages)
                    math_result = ""
                    math_keywords = ["solve", "calculate", "compute",
                                     "=", "x^", "x²", "sqrt",
                                     "integral", "derivative", "%"]
                    if any(kw in user_input.lower()
                           for kw in math_keywords):
                        math_result = solve_math(
                            user_input.replace("solve","").strip())
                    st.session_state.chat_messages.append({
                        "role": "assistant",
                        "content": ai_reply,
                        "math_result": math_result
                    })
                    st.rerun()
                except Exception as e:
                    st.error(f"❌ Error: {str(e)}")
        elif send_btn:
            st.warning("⚠️ Please type a message first!")
        st.markdown(f"""
                    <div style='margin-bottom:1.2rem;'>
          <div style='font-weight:700;font-size:1rem;color:{TEXT};margin-bottom:0.3rem;'>
            🔍 AI-Powered Web Research
          </div>
          <div style='color:{SUBTEXT};font-size:0.88rem;'>
            Enter a topic — our agent searches 5+ live sources and writes a structured report.
          </div>
        </div>
        """, unsafe_allow_html=True)

        r1, r2, r3 = st.columns([0.2, 4, 0.2])
        with r2:
            res_topic = st.text_input("",
                placeholder="💡  e.g. Impact of Quantum Computing on Cryptography",
                label_visibility="collapsed", key="res_input")
            st.markdown("<div style='height:0.4rem'></div>", unsafe_allow_html=True)
            res_btn = st.button("🚀  Generate Research Report", type="primary", key="res_btn")

        st.markdown(f"""
        <div style='display:grid;grid-template-columns:repeat(3,1fr);gap:0.8rem;margin:1.5rem 0;'>
          <div style='background:{CARD_BG};border:1px solid {BORDER};border-radius:12px;
                      padding:1rem;text-align:center;'>
            <div style='font-size:1.5rem;'>⚡</div>
            <div style='font-weight:700;font-size:0.88rem;color:{TEXT};margin-top:0.3rem;'>~30s</div>
            <div style='font-size:0.76rem;color:{SUBTEXT};'>Fast inference</div>
          </div>
          <div style='background:{CARD_BG};border:1px solid {BORDER};border-radius:12px;
                      padding:1rem;text-align:center;'>
            <div style='font-size:1.5rem;'>🌐</div>
            <div style='font-weight:700;font-size:0.88rem;color:{TEXT};margin-top:0.3rem;'>5+ Sources</div>
            <div style='font-size:0.76rem;color:{SUBTEXT};'>Real-time web</div>
          </div>
          <div style='background:{CARD_BG};border:1px solid {BORDER};border-radius:12px;
                      padding:1rem;text-align:center;'>
            <div style='font-size:1.5rem;'>📄</div>
            <div style='font-weight:700;font-size:0.88rem;color:{TEXT};margin-top:0.3rem;'>PDF Export</div>
            <div style='font-size:0.76rem;color:{SUBTEXT};'>Download ready</div>
          </div>
        </div>
        """, unsafe_allow_html=True)

        if st.session_state.history:
            st.markdown(f"<div style='font-weight:700;color:{TEXT};font-size:0.9rem;"
                        f"margin-bottom:0.5rem;'>📂 Recent Reports</div>",
                        unsafe_allow_html=True)
            for item in reversed(st.session_state.history[-4:]):
                st.markdown(f"""
                <div class='hist-item'>
                  <div class='hist-title'>📄 {item['topic']}</div>
                  <div class='hist-date'>{item['time']}</div>
                </div>""", unsafe_allow_html=True)

        if res_btn and res_topic:
            with st.spinner("🤖 AI Agent is researching... ⏳"):
                try:
                    report, steps = run_research(res_topic)
                    st.session_state.history.append({
                        "topic": res_topic, "report": report,
                        "steps": steps,
                        "time": datetime.now().strftime("%b %d, %H:%M")
                    })
                    st.session_state.current_report = {
                        "topic": res_topic, "report": report, "steps": steps
                    }
                    st.rerun()
                except Exception as e:
                    st.error(f"❌ Error: {str(e)}")
        elif res_btn:
            st.warning("⚠️ Please enter a research topic!")

# ══════════════════════════════════════════════════════════════════════════════
# HOW IT WORKS PAGE
# ══════════════════════════════════════════════════════════════════════════════
elif st.session_state.page == "how" and not st.session_state.current_report:

    st.markdown(f"""
    <div style='text-align:center; padding:2.5rem 0 1.5rem 0;'>
        <h1 style='font-size:2.2rem; font-weight:800; color:{TEXT};'>
            How ResearchAI Works</h1>
        <p style='color:{SUBTEXT}; font-size:1rem;
                  max-width:500px; margin:0.8rem auto;'>
            From topic to professional report in 4 simple steps</p>
    </div>
    """, unsafe_allow_html=True)

    s1,s2,s3,s4 = st.columns(4)
    for col,num,icon,title,desc in [
        (s1,"1","📝","Enter Topic","Type any research topic you want to learn about"),
        (s2,"2","🔍","AI Searches","Agent searches internet using Tavily API"),
        (s3,"3","🧠","AI Analyzes","Groq LLaMA3 synthesizes all search results"),
        (s4,"4","📄","Report Ready","Structured professional report in seconds"),
    ]:
        with col:
            st.markdown(f"""
            <div class="step-card">
                <div class="step-num">{num}</div>
                <div style='font-size:1.9rem;margin-bottom:0.5rem;'>{icon}</div>
                <div class="step-title">{title}</div>
                <div class="step-desc">{desc}</div>
            </div>""", unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown(f"""
    <div class="card">
        <div style='font-size:1.1rem;font-weight:700;color:{TEXT};
                    margin-bottom:1.2rem;'>⚡ Tech Stack</div>
        <div style='display:grid;grid-template-columns:repeat(3,1fr);gap:0.8rem;'>
        {"".join([
            f"<div style='padding:0.9rem;background:{CARD2};border-radius:10px;"
            f"border:1px solid {BORDER};'>"
            f"<div style='font-weight:700;color:{ACCENT};margin-bottom:0.3rem;"
            f"font-size:0.95rem;'>{ic} {nm}</div>"
            f"<div style='font-size:0.82rem;color:{SUBTEXT};'>{ds}</div></div>"
            for ic,nm,ds in [
                ("🦜","LangChain","Framework connecting all AI components"),
                ("🕸️","LangGraph","Builds the multi-step agent workflow"),
                ("🤖","Groq LLaMA3","Fast LLM for writing research reports"),
                ("🔍","Tavily API","Real-time web search for current data"),
                ("🚀","Streamlit","Web UI deployed on Streamlit Cloud"),
                ("📄","ReportLab","Professional PDF report generation"),
            ]
        ])}
        </div>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)
    c1,c2,c3 = st.columns([1,2,1])
    with c2:
        if st.button("🔍  Try ResearchAI Now →", type="primary", key="try"):
            st.session_state.page = "home"
            st.rerun()

# ══════════════════════════════════════════════════════════════════════════════
# REPORT PAGE
# ══════════════════════════════════════════════════════════════════════════════
elif st.session_state.current_report:
    cur = st.session_state.current_report
    m,s = st.columns([3,1])

    with m:
        st.markdown(f"""
        <div class="card">
            <div style='display:flex;justify-content:space-between;
                        align-items:flex-start;'>
                <div>
                    <div style='font-size:1.25rem;font-weight:700;
                                color:{TEXT};'>📄 {cur['topic']}</div>
                    <div style='font-size:0.85rem;color:{SUBTEXT};
                                margin-top:0.3rem;'>
                        {datetime.now().strftime("%B %d, %Y at %H:%M")}
                        &nbsp;·&nbsp; Groq LLaMA3 + Tavily
                    </div>
                </div>
                <div style='background:rgba(16,185,129,0.1);
                            color:#10b981!important;
                            border:1px solid rgba(16,185,129,0.3);
                            border-radius:20px;padding:0.3rem 0.8rem;
                            font-size:0.8rem;font-weight:600;'>
                    ✅ Complete
                </div>
            </div>
        </div>
        <div class="card">
            <div class="report-text">{cur['report']}</div>
        </div>
        """, unsafe_allow_html=True)
        if st.button("🔍  New Research", type="primary", key="new_res"):
            st.session_state.current_report = None
            st.session_state.page = "home"
            st.rerun()

    with s:
        st.markdown(f"""
        <div class="card">
            <div style='font-weight:700;font-size:0.95rem;
                        color:{TEXT};margin-bottom:0.8rem;'>
                🤖 Agent Steps</div>
        """, unsafe_allow_html=True)
        for step in cur['steps']:
            st.markdown(f'<div class="badge">✅ {step}</div>',
                        unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)
        st.markdown("<br>", unsafe_allow_html=True)
        pdf = generate_pdf(cur['topic'], cur['report'])
        st.download_button(
            label="⬇️ Download PDF Report",
            data=pdf,
            file_name=f"{cur['topic'][:25]}_report.pdf",
            mime="application/pdf", key="dl_pdf")

st.markdown("</div>", unsafe_allow_html=True)

# Footer
st.markdown(f"""
<div style='
  margin-top:4rem;
  background:{'#0a0d14' if dark else '#1e293b'};
  border-top:3px solid {ACCENT};
  padding:2.2rem 2rem 1.6rem 2rem;
  text-align:center;
'>
  <div style='font-size:1.05rem;font-weight:800;color:#ffffff;margin-bottom:0.35rem;'>🔬 ResearchAI</div>
  <div style='font-size:0.82rem;color:rgba(255,255,255,0.55);margin-bottom:1rem;'>
    AI-powered research reports — instantly.
  </div>
  <div style='display:flex;justify-content:center;gap:1.8rem;margin-bottom:1.1rem;'>
    <a href='https://github.com/nevedhya03-dotcom' target='_blank'
       style='color:rgba(255,255,255,0.7);text-decoration:none;font-size:0.83rem;font-weight:500;
              transition:color 0.18s;'>GitHub</a>
    <span style='color:rgba(255,255,255,0.25);'>·</span>
    <span style='color:rgba(255,255,255,0.55);font-size:0.83rem;'>Groq LLaMA3 + Tavily</span>
    <span style='color:rgba(255,255,255,0.25);'>·</span>
    <span style='color:rgba(255,255,255,0.55);font-size:0.83rem;'>LangGraph + Streamlit</span>
  </div>
  <div style='font-size:0.75rem;color:rgba(255,255,255,0.3);'>
    Built with ❤️ by
    <a href='https://github.com/nevedhya03-dotcom' target='_blank'
       style='color:{ACCENT};text-decoration:none;font-weight:600;'>Nevedhya Patni</a>
  </div>
</div>
""", unsafe_allow_html=True)