import streamlit as st
from agent_core import run_research
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_LEFT, TA_CENTER
import io
from datetime import datetime

# ── PDF Generator ──────────────────────────────────────────────────────────────
def generate_pdf(topic, report_text):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
        rightMargin=2*cm, leftMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm)

    title_s  = ParagraphStyle("t", fontName="Helvetica-Bold",
        fontSize=20, textColor=colors.HexColor("#2563eb"),
        alignment=TA_CENTER, spaceAfter=8)
    topic_s  = ParagraphStyle("tp", fontName="Helvetica-Bold",
        fontSize=13, textColor=colors.HexColor("#1e293b"),
        alignment=TA_CENTER, spaceAfter=6)
    meta_s   = ParagraphStyle("m", fontName="Helvetica-Oblique",
        fontSize=9, textColor=colors.HexColor("#64748b"),
        alignment=TA_CENTER, spaceAfter=16)
    body_s   = ParagraphStyle("b", fontName="Helvetica",
        fontSize=10, leading=16,
        textColor=colors.HexColor("#1e293b"), spaceAfter=6)

    story = [
        Paragraph("AI Research Agent", title_s),
        Paragraph(f"Report: {topic}", topic_s),
        Paragraph("Generated by AI Research Agent — Powered by Groq LLaMA3 + Tavily", meta_s),
        HRFlowable(width="100%", thickness=0.8,
                   color=colors.HexColor("#2563eb"), spaceAfter=14),
    ]
    for line in report_text.split('\n'):
        line = line.strip().replace('**','').replace('•','-')
        story.append(Paragraph(line, body_s) if line else Spacer(1, 5))
    doc.build(story)
    buffer.seek(0)
    return buffer

# ── Page Config ────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="AI Research Agent",
    page_icon="🔬",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ── Theme State ────────────────────────────────────────────────────────────────
if "dark_mode" not in st.session_state:
    st.session_state.dark_mode = False
if "history" not in st.session_state:
    st.session_state.history = []

dark = st.session_state.dark_mode

# ── Theme Colors ───────────────────────────────────────────────────────────────
if dark:
    BG          = "#0f172a"
    SIDEBAR_BG  = "#1e293b"
    CARD_BG     = "#1e293b"
    TEXT        = "#f1f5f9"
    SUBTEXT     = "#94a3b8"
    BORDER      = "#334155"
    ACCENT      = "#3b82f6"
    NAV_BG      = "#1e293b"
    INPUT_BG    = "#0f172a"
else:
    BG          = "#f8fafc"
    SIDEBAR_BG  = "#ffffff"
    CARD_BG     = "#ffffff"
    TEXT        = "#0f172a"
    SUBTEXT     = "#64748b"
    BORDER      = "#e2e8f0"
    ACCENT      = "#2563eb"
    NAV_BG      = "#ffffff"
    INPUT_BG    = "#f8fafc"

# ── CSS ────────────────────────────────────────────────────────────────────────
st.markdown(f"""
<style>
/* Global */
.stApp {{
    background-color: {BG};
    color: {TEXT};
}}

/* Hide default streamlit header */
header[data-testid="stHeader"] {{
    background-color: {NAV_BG};
    border-bottom: 1px solid {BORDER};
}}

/* Sidebar */
section[data-testid="stSidebar"] {{
    background-color: {SIDEBAR_BG};
    border-right: 1px solid {BORDER};
    padding-top: 0;
}}

section[data-testid="stSidebar"] * {{
    color: {TEXT} !important;
}}

/* Navigation bar */
.navbar {{
    background: {NAV_BG};
    border-bottom: 1px solid {BORDER};
    padding: 0.8rem 2rem;
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin: -1rem -1rem 1.5rem -1rem;
}}

.nav-brand {{
    font-size: 1.2rem;
    font-weight: 700;
    color: {ACCENT};
    display: flex;
    align-items: center;
    gap: 0.5rem;
}}

.nav-links {{
    display: flex;
    gap: 2rem;
    color: {SUBTEXT};
    font-size: 0.9rem;
}}

.nav-links a {{
    color: {SUBTEXT};
    text-decoration: none;
    font-weight: 500;
}}

.nav-links a:hover {{
    color: {ACCENT};
}}

/* Cards */
.report-card {{
    background: {CARD_BG};
    border: 1px solid {BORDER};
    border-radius: 12px;
    padding: 1.5rem;
    margin-bottom: 1rem;
    box-shadow: 0 1px 3px rgba(0,0,0,0.05);
}}

/* Input */
.stTextInput > div > div > input {{
    background: {INPUT_BG};
    border: 1.5px solid {BORDER};
    border-radius: 8px;
    color: {TEXT};
    font-size: 0.95rem;
    padding: 0.5rem 1rem;
}}

.stTextInput > div > div > input:focus {{
    border-color: {ACCENT};
    box-shadow: 0 0 0 3px rgba(37,99,235,0.1);
}}

/* Research button */
.stButton > button {{
    background: {ACCENT};
    color: white;
    border: none;
    border-radius: 8px;
    padding: 0.5rem 1.5rem;
    font-size: 0.95rem;
    font-weight: 600;
    width: 100%;
    transition: all 0.2s;
}}

.stButton > button:hover {{
    opacity: 0.9;
    transform: translateY(-1px);
    box-shadow: 0 4px 12px rgba(37,99,235,0.3);
}}

/* Download button */
.stDownloadButton > button {{
    background: white;
    color: {ACCENT};
    border: 1.5px solid {ACCENT};
    border-radius: 8px;
    font-weight: 600;
    width: 100%;
}}

/* History item */
.history-item {{
    padding: 0.7rem 0.8rem;
    border-radius: 8px;
    margin-bottom: 0.4rem;
    border: 1px solid {BORDER};
    background: {BG};
    cursor: pointer;
    transition: all 0.2s;
}}

.history-item:hover {{
    border-color: {ACCENT};
    background: rgba(37,99,235,0.05);
}}

.history-title {{
    font-size: 0.85rem;
    font-weight: 600;
    color: {TEXT};
}}

.history-date {{
    font-size: 0.75rem;
    color: {SUBTEXT};
    margin-top: 2px;
}}

/* Step badge */
.step-badge {{
    display: inline-block;
    background: rgba(37,99,235,0.1);
    color: {ACCENT};
    border-radius: 6px;
    padding: 0.2rem 0.6rem;
    font-size: 0.8rem;
    font-weight: 600;
    margin-bottom: 0.5rem;
}}

/* Section titles */
.section-title {{
    font-size: 1.3rem;
    font-weight: 700;
    color: {TEXT};
    margin-bottom: 0.3rem;
}}

.section-sub {{
    font-size: 0.9rem;
    color: {SUBTEXT};
    margin-bottom: 1.2rem;
}}

/* Features row */
.feature-grid {{
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 1rem;
    margin-top: 1rem;
}}

.feature-card {{
    background: {CARD_BG};
    border: 1px solid {BORDER};
    border-radius: 10px;
    padding: 1rem;
    text-align: center;
}}

.feature-icon {{
    font-size: 1.5rem;
    margin-bottom: 0.5rem;
}}

.feature-title {{
    font-size: 0.9rem;
    font-weight: 600;
    color: {TEXT};
}}

.feature-desc {{
    font-size: 0.8rem;
    color: {SUBTEXT};
    margin-top: 0.3rem;
}}

/* Report display */
.report-body {{
    font-size: 0.95rem;
    line-height: 1.7;
    color: {TEXT};
    white-space: pre-wrap;
}}

/* All text */
p, h1, h2, h3, label, div {{
    color: {TEXT} !important;
}}

.subtext {{
    color: {SUBTEXT} !important;
}}
</style>
""", unsafe_allow_html=True)

# ── Navigation Bar ─────────────────────────────────────────────────────────────
st.markdown(f"""
<div class="navbar">
    <div class="nav-brand">
        🔬 ResearchAI
    </div>
    <div class="nav-links">
        <a href="#">Home</a>
        <a href="#">How it works</a>
        <a href="https://github.com/nevedhya03-dotcom" target="_blank">GitHub</a>
    </div>
</div>
""", unsafe_allow_html=True)

# ── Sidebar ────────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown(f"""
    <div style='padding:1rem 0; border-bottom:1px solid {BORDER};
                display:flex; align-items:center; gap:0.5rem;
                margin-bottom:1rem;'>
        <span style='font-size:1.1rem; font-weight:700; 
                     color:{ACCENT};'>🔬 ResearchAI</span>
    </div>
    """, unsafe_allow_html=True)

    # Dark/Light Toggle
    col_a, col_b = st.columns([3, 1])
    with col_a:
        st.markdown(f"<span style='font-size:0.85rem; color:{SUBTEXT};'>"
                    f"{'🌙 Dark Mode' if dark else '☀️ Light Mode'}</span>",
                    unsafe_allow_html=True)
    with col_b:
        if st.button("🌓"):
            st.session_state.dark_mode = not st.session_state.dark_mode
            st.rerun()

    st.markdown("---")

    # Search History
    st.markdown(f"""
    <div style='font-size:0.8rem; font-weight:600; 
                color:{SUBTEXT}; margin-bottom:0.8rem;
                text-transform:uppercase; letter-spacing:0.05em;'>
        📋 Research History
    </div>
    """, unsafe_allow_html=True)

    if st.session_state.history:
        for i, item in enumerate(reversed(st.session_state.history)):
            st.markdown(f"""
            <div class="history-item">
                <div class="history-title">📄 {item['topic'][:28]}...</div>
                <div class="history-date">🕐 {item['time']}</div>
            </div>
            """, unsafe_allow_html=True)
    else:
        st.markdown(f"""
        <div style='text-align:center; padding:2rem 1rem;
                    color:{SUBTEXT}; font-size:0.85rem;'>
            No research yet.<br>Start your first research above!
        </div>
        """, unsafe_allow_html=True)

    st.markdown("---")
    st.markdown(f"""
    <div style='font-size:0.8rem; color:{SUBTEXT}; text-align:center;'>
        Built by <b>Nevedhya Patni</b><br>
        <a href='https://github.com/nevedhya03-dotcom' 
           style='color:{ACCENT};'>GitHub Profile</a>
    </div>
    """, unsafe_allow_html=True)

# ── Main Content ───────────────────────────────────────────────────────────────
if not st.session_state.history or "current_report" not in st.session_state:

    # Hero Section
    st.markdown(f"""
    <div style='text-align:center; padding:2rem 0 1rem 0;'>
        <h1 style='font-size:2.5rem; font-weight:800; color:{TEXT};'>
            Write Better Reports with
            <span style='color:{ACCENT};'> ResearchAI</span>
        </h1>
        <p style='color:{SUBTEXT}; font-size:1.1rem; max-width:600px; margin:0 auto;'>
            Enter any topic and our AI will search the internet,
            analyze sources, and write a professional research report instantly.
        </p>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # Search Box
    col1, col2, col3 = st.columns([1, 3, 1])
    with col2:
        topic = st.text_input(
            "",
            placeholder="e.g. Latest trends in Generative AI 2026",
            label_visibility="collapsed"
        )
        search_btn = st.button("🔍  Start Research", type="primary")

    st.markdown("<br>", unsafe_allow_html=True)

    # Feature Cards
    st.markdown(f"""
    <div class="feature-grid">
        <div class="feature-card">
            <div class="feature-icon">⚡</div>
            <div class="feature-title">Time-Saving</div>
            <div class="feature-desc">
                Get full research reports in under 30 seconds
            </div>
        </div>
        <div class="feature-card">
            <div class="feature-icon">🎯</div>
            <div class="feature-title">High Accuracy</div>
            <div class="feature-desc">
                Powered by real-time web search via Tavily API
            </div>
        </div>
        <div class="feature-card">
            <div class="feature-icon">📄</div>
            <div class="feature-title">PDF Export</div>
            <div class="feature-desc">
                Download professional PDF reports instantly
            </div>
        </div>
    </div>
    """, unsafe_allow_html=True)

    # Research Logic
    if search_btn and topic:
        with st.spinner("🤖 AI Agent is researching..."):
            try:
                report, steps = run_research(topic)

                # Save to history
                st.session_state.history.append({
                    "topic": topic,
                    "report": report,
                    "steps": steps,
                    "time": datetime.now().strftime("%b %d, %H:%M")
                })
                st.session_state.current_report = {
                    "topic": topic,
                    "report": report,
                    "steps": steps
                }
                st.rerun()

            except Exception as e:
                st.error(f"❌ Error: {str(e)}")

    elif search_btn:
        st.warning("⚠️ Please enter a research topic!")

else:
    # ── Report View ────────────────────────────────────────────────────────────
    current = st.session_state.current_report

    col_main, col_side = st.columns([3, 1])

    with col_main:
        # Report header
        st.markdown(f"""
        <div class="report-card">
            <div style='display:flex; justify-content:space-between;
                        align-items:flex-start;'>
                <div>
                    <div class="section-title">
                        📄 {current['topic']}
                    </div>
                    <div class="section-sub">
                        Generated on {datetime.now().strftime("%B %d, %Y at %H:%M")}
                    </div>
                </div>
            </div>
        </div>
        """, unsafe_allow_html=True)

        # Report body
        st.markdown(f"""
        <div class="report-card">
            <div class="report-body">{current['report']}</div>
        </div>
        """, unsafe_allow_html=True)

        # New research button
        if st.button("🔍 New Research"):
            del st.session_state.current_report
            st.rerun()

    with col_side:
        # Agent Steps
        st.markdown(f"""
        <div class="report-card">
            <div style='font-weight:700; margin-bottom:0.8rem; 
                        color:{TEXT};'>
                🤖 What Agent Did
            </div>
        """, unsafe_allow_html=True)

        for step in current['steps']:
            st.markdown(f"""
            <div class="step-badge">✅ {step}</div><br>
            """, unsafe_allow_html=True)

        st.markdown("</div>", unsafe_allow_html=True)

        # Download PDF
        st.markdown("<br>", unsafe_allow_html=True)
        pdf = generate_pdf(current['topic'], current['report'])
        st.download_button(
            label="⬇️ Download PDF",
            data=pdf,
            file_name=f"{current['topic'][:25]}_report.pdf",
            mime="application/pdf"
        )